@startuml
actor Formateur
rectangle pkg_competences {
left to right direction
  usecase "gestion des niveaux de compétences" as UC1

}

actor Responsable_de_formation
rectangle pkg_competences {
    left to right direction
    usecase "gestion des compétences" as UC3
    usecase "gestion des Modules" as UC4
    usecase "gestion des filières" as UC5

}


Formateur -- UC1 
Formateur -- UC3

Responsable_de_formation -- UC3
Responsable_de_formation -- UC4
Responsable_de_formation -- UC5





@enduml